import { NextResponse } from "next/server";
import Groq from "groq-sdk";

// Ensure the endpoint is executed dynamically, as it depends on API keys and requests
export const dynamic = "force-dynamic";

export async function POST(request: Request) {
  try {
    const body = await request.json().catch(() => null);
    if (!body) {
      return NextResponse.json(
        { error: "Invalid JSON request body." },
        { status: 400 }
      );
    }

    const { userInput, mode, party1Email, party2Email } = body;

    // Validate inputs
    if (!userInput || typeof userInput !== "string") {
      return NextResponse.json(
        { error: "Missing or invalid 'userInput' field." },
        { status: 400 }
      );
    }

    if (!mode || (mode !== "pro" && mode !== "fun")) {
      return NextResponse.json(
        { error: "Invalid 'mode'. Allowed values are 'pro' or 'fun'." },
        { status: 400 }
      );
    }

    const apiKey = process.env.GROQ_API_KEY;
    if (!apiKey || apiKey === "your-groq-api-key-here") {
      return NextResponse.json(
        { error: "Groq API key is not configured on the server." },
        { status: 500 }
      );
    }

    // Initialize Groq client
    const groq = new Groq({ apiKey });

    // Determine the system instructions based on the selected mode
    let systemInstruction = "";
    if (mode === "pro") {
      systemInstruction = 
        "You are an elite corporate legal analyst under the Indian Contract Act. " +
        "Convert the user's input into a strictly formatted, legally sound micro-contract written in structured Markdown.\n\n" +
        "CRITICAL FORMATTING RULES:\n" +
        "1. Start with a bold, uppercase title: `# MEMORANDUM OF AGREEMENT`.\n" +
        "2. Use `---` dividers after the title and between major sections.\n" +
        "3. Use `## ` (Heading 2) for all subheadings (e.g., `## PARTIES & RECITALS`, `## SCOPE OF WORK`, `## PAYMENT & FINANCIAL TERMS`, `## DEFAULT & REMEDIES`, `## JURISDICTION`).\n" +
        "4. Bold all party names, key terms, amounts, deadlines, and percentages (e.g., **Service Provider**, **Client**, **INR 50,000**, **50% Upfront**).\n" +
        "5. Underline or semi-bold important clause headers within bullet points (e.g., - **Scope of Services:** ...).\n" +
        "6. Include a dedicated `## SIGNATURE & VERIFICATION` section at the end with signature lines and email addresses.\n\n" +
        "Maintain authoritative, precise legal language with clear structure.";
    } else {
      systemInstruction = 
        "Act as a modern, witty Gen-Z writer drafting a casual agreement ('pact'). Balance light humor with clear communication of terms. Use modern internet vernacular but avoid exaggerated slang. Strict constraints: Maximum of 2 emojis in the entire document.\n\n" +
        "CRITICAL MARKDOWN FORMATTING RULES FOR VISUAL STANDOUT:\n" +
        "1. Start with a bold title: `# CASUAL PACT AGREEMENT`.\n" +
        "2. Use `---` dividers between sections.\n" +
        "3. ALWAYS format major section subheadings using `## ` (Heading 2) e.g., `## 1. The Vibe`, `## 2. The Deal`, `## 3. The Penalty`, `## 4. Execution & Seal`.\n" +
        "4. BOLD all party names, promises, penalties, and key terms (`**name**`, `**action**`, `**penalty**`) so they stand out clearly in rich text format.\n" +
        "5. Keep section paragraphs clean, distinct, and well-spaced for maximum readability.";
    }

    // Call Groq API
    const chatCompletion = await groq.chat.completions.create({
      messages: [
        {
          role: "system",
          content: systemInstruction
        },
        {
          role: "user",
          content: userInput,
        }
      ],
      model: "llama-3.3-70b-versatile",
      temperature: 0.2,
    });

    const generatedText = chatCompletion.choices[0]?.message?.content;
    if (!generatedText) {
      throw new Error("No content generated by Groq.");
    }

    return NextResponse.json({
      success: true,
      markdown: generatedText,
    });

  } catch (error: any) {
    console.error("Groq Generation API Error:", error);

    // Check if the error is due to expired or invalid API key
    const isExpiredKey =
      error?.status === 401 ||
      error?.statusCode === 401 ||
      /expired_api_key|invalid_api_key|Invalid API Key/i.test(
        error?.message || JSON.stringify(error)
      );

    if (isExpiredKey) {
      return NextResponse.json(
        {
          error:
            "The Groq AI API Key has expired or is invalid. Please generate a fresh free API Key at https://console.groq.com/keys and update GROQ_API_KEY in Netlify / .env.local.",
        },
        { status: 401 }
      );
    }

    // Check if the error is due to API rate limiting
    const isRateLimit =
      error?.status === 429 ||
      error?.statusCode === 429 ||
      /429|rate_limit_exceeded/i.test(error?.message || "");

    if (isRateLimit) {
      return NextResponse.json(
        { error: "Traffic spike. Please wait 15 seconds." },
        { status: 429 }
      );
    }

    return NextResponse.json(
      { error: error?.message || "Failed to generate legal contract content." },
      { status: 500 }
    );
  }
}
