import { NextResponse } from "next/server";
import Groq from "groq-sdk";

// Ensure the endpoint is executed dynamically, as it depends on API keys and requests
export const dynamic = "force-dynamic";

export async function POST(request: Request) {
  try {
    const body = await request.json().catch(() => null);
    if (!body) {
      return NextResponse.json(
        { error: "Invalid JSON request body." },
        { status: 400 }
      );
    }

    const { userInput, mode, party1Email, party2Email } = body;

    // Validate inputs
    if (!userInput || typeof userInput !== "string") {
      return NextResponse.json(
        { error: "Missing or invalid 'userInput' field." },
        { status: 400 }
      );
    }

    if (!mode || (mode !== "pro" && mode !== "fun")) {
      return NextResponse.json(
        { error: "Invalid 'mode'. Allowed values are 'pro' or 'fun'." },
        { status: 400 }
      );
    }

    const apiKey = process.env.GROQ_API_KEY;
    if (!apiKey || apiKey === "your-groq-api-key-here") {
      return NextResponse.json(
        { error: "Groq API key is not configured on the server." },
        { status: 500 }
      );
    }

    // Initialize Groq client
    const groq = new Groq({ apiKey });

    // Determine the system instructions based on the selected mode
    let systemInstruction = "";
    if (mode === "pro") {
      systemInstruction = 
        "You are an elite corporate lawyer under the Indian Contract Act. " +
        "Your task is to convert the user's input into a strictly formatted, legally sound micro-contract written in highly structured Markdown.\n\n" +
        "CRITICAL FORMATTING RULES:\n" +
        "1. Start with a massive centered title using `# TITLE OF AGREEMENT`.\n" +
        "2. Use `---` (horizontal rule) after the title and between major sections to separate them.\n" +
        "3. Use `## ` (Heading 2) for all section titles (e.g., `## PARTIES INVOLVED`, `## SCOPE OF WORK`, `## PAYMENT TERMS`, `## JURISDICTION`).\n" +
        "4. Bold all party names, important dates, and monetary amounts (e.g., **INR 15,000**).\n" +
        "5. Use bullet points (`-`) or numbered lists for clauses so it is highly readable.\n" +
        "6. Do not output plain unformatted text blocks. Everything must be structured legally with clear spacing and line breaks.\n\n" +
        "CRITICAL SIGNATURE REQUIREMENT:\n" +
        "At the very bottom of the document, you MUST include a dedicated `## SIGNATURES` section. " +
        "Provide clear execution lines for both parties, explicitly writing out their full names and the provided email addresses underneath a signature line (e.g., `_______________________\\n**Name**\\n*Email*`). " +
        "If email addresses are provided in the input, they must be included in the signature block.\n\n" +
        "Use precise legal terminology and a highly professional tone.";
    } else {
      systemInstruction = 
        "Act as a modern, witty Gen-Z writer drafting a casual agreement ('pact'). Balance light humor with clear communication of the actual terms. Use modern internet vernacular but avoid exaggerated slang. Strict constraints: Maximum of 2 emojis in the entire document. Maintain clear markdown formatting for sections (e.g., 'The Vibe', 'The Deal', 'The Penalty'). Keep it structured, easily readable, and playfully serious rather than overly comedic.";
    }

    // Call Groq API
    const chatCompletion = await groq.chat.completions.create({
      messages: [
        {
          role: "system",
          content: systemInstruction
        },
        {
          role: "user",
          content: userInput,
        }
      ],
      model: "llama-3.3-70b-versatile",
      temperature: 0.2,
    });

    const generatedText = chatCompletion.choices[0]?.message?.content;
    if (!generatedText) {
      throw new Error("No content generated by Groq.");
    }

    return NextResponse.json({
      success: true,
      markdown: generatedText,
    });

  } catch (error: any) {
    console.error("Groq Generation API Error:", error);

    // Check if the error is due to API rate limiting
    const isRateLimit =
      error?.status === 429 ||
      error?.statusCode === 429 ||
      /429|rate_limit_exceeded/i.test(error?.message || "");

    if (isRateLimit) {
      return NextResponse.json(
        { error: "Traffic spike. Please wait 15 seconds." },
        { status: 429 }
      );
    }

    return NextResponse.json(
      { error: error instanceof Error ? error.message : "Internal Server Error" },
      { status: 500 }
    );
  }
}
